[package]
name = "pallet-bounties"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet to manage bounties"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-std = { version = "3.0.0", default-features = false, path = "../../primitives/std" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../primitives/runtime" }
frame-support = { version = "3.0.0", default-features = false, path = "../support" }
frame-system = { version = "3.0.0", default-features = false, path = "../system" }
pallet-social-network-dao = { version = "3.0.0", default-features = false, path = "../social-network-dao" }

frame-benchmarking = { version = "3.0.0", default-features = false, path = "../benchmarking", optional = true }

[dev-dependencies]
sp-io ={ version = "3.0.0", path = "../../primitives/io" }
sp-core = { version = "3.0.0", path = "../../primitives/core" }
sp-storage = { version = "3.0.0", path = "../../primitives/storage" }
pallet-balances = { version = "3.0.0", path = "../balances" }
pallet-assets = { version = "3.0.0", path = "../assets" }
pallet-social-guardians = { version = "0.1.0", path = "../social-guardians" }
pallet-session = { default-features = false, version = "3.0.0", path = "../session" }
pallet-staking = { version = "3.0.0", default-features = false, path = "../staking" }
pallet-staking-reward-curve = { version = "3.0.0", path = "../staking/reward-curve" }
pallet-timestamp = { default-features = false, version = "3.0.0", path = "../timestamp" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-social-network-dao/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
