name: Rust Build

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Install rust
      uses: hecrj/setup-rust-action@v1.3.4
      with:
        rust-version: stable
        targets: x86_64-unknown-linux-gnu
        components: clippy, rustfmt

    - name: Build
      run: cargo check --workspace --all-targets
      
    - name: Run tests
      run: cargo test --workspace --all-targets --all-features
