name: Rust Build

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Update Stable Rust
      run: rustup toolchain update stable
      
    - name: Install Nightly
      uses: hecrj/setup-rust-action@v1.3.4
      with:
        rust-version: nightly
        targets: x86_64-unknown-linux-gnu, wasm32-unknown-unknown
        components: clippy, rustfmt

    - name: cargo check --workspace --all-targets
      run: cargo check --workspace --all-targets
      
    - name: cargo test --workspace --all-targets --all-features
      run: cargo test --workspace --all-targets --all-features
