name: Rust Build

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust nightly
      run: rustup toolchain install nightly
    - name: Install WASM toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --workspace --verbose
