name: Rust Build

on:
  push:
    branches:
    - master
    - v3
  pull_request:
    branches:
    - master
    - v3

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

    - name: Build
#      run: cargo check --workspace --all-targets
      run: cargo check
      
    - name: Run tests
#      run: cargo test --workspace --all-targets --all-features
      run: cargo test
